RULESETS = {
    "R0": [],
    "R1": [
        "usa palabras comunes",
        "evita tecnicismos innecesarios",
        "reemplaza palabras difíciles por palabras simples",
    ],
    "R2": [
        "usa palabras comunes",
        "evita tecnicismos innecesarios",
        "reemplaza palabras difíciles por palabras simples",
        "usa oraciones cortas",
        "expresa una idea por oración",
        "prefiere voz activa",
        "divide oraciones largas",
    ],
    "R3": [
        "usa palabras comunes",
        "evita tecnicismos innecesarios",
        "reemplaza palabras difíciles por palabras simples",
        "usa oraciones cortas",
        "expresa una idea por oración",
        "prefiere voz activa",
        "divide oraciones largas",
        "mantén la idea principal",
        "elimina detalles secundarios si estorban",
        "evita ambigüedades",
        "explica conceptos abstractos de forma simple",
        "mantén coherencia temporal",
    ],
    "R4": [
        "usa palabras comunes",
        "evita tecnicismos innecesarios",
        "reemplaza palabras difíciles por palabras simples",
        "usa oraciones cortas",
        "expresa una idea por oración",
        "prefiere voz activa",
        "divide oraciones largas",
        "mantén la idea principal",
        "elimina detalles secundarios si estorban",
        "evita ambigüedades",
        "explica conceptos abstractos de forma simple",
        "mantén coherencia temporal",
        "aclara números si aparecen",
        "ordena de lo más importante a lo menos importante",
        "usa tono directo y claro",
    ],
}